### ISSUE TITLE
Deploy fails

### ISSUE THREAD

**Issue by fdietze** [social-protocols/social-protocols.github.io#3]
@johnwarden The reference commit in the theme submodule doesn't exist anymore:

https://github.com/social-protocols/social-protocols.github.io/actions/runs/5263123115/jobs/9512968696#step:2:175

But updating locally to `ae7a321770ab87cba6593a1639116bb117d9ba4e` seems to give me a broken site:

![image](https://github.com/social-protocols/social-protocols.github.io/assets/1186516/135e6367-acb9-4baa-8d7d-a10950976872)

any ideas?

**Comment by johnwarden** [comment]
Okay, the problem was simply that I had not pushed the latest commit of github.com/johnwarden/hugo-theme-stack. This is fixed.
